Switch to using `devbox services pcport`

diff --git a/plugins/ca-common/bin/run-with-services-up b/plugins/ca-common/bin/run-with-services-up
--- a/plugins/ca-common/bin/run-with-services-up
+++ b/plugins/ca-common/bin/run-with-services-up
@@ -67,19 +67,7 @@ main() {
   output=$("${devbox_args[@]}" 2>&1)
 
   # Get the process-compose port from the output.
-  local pcport_output
-  pcport_output=$(echo "$output" | grep -oE "running on port [0-9]+" | grep -oE "[0-9]+")
-  export PCPORT="$pcport_output"
-  if [ -n "$PCPORT" ]; then
-      echo "Process-compose is running on port: $PCPORT"
-  else
-      echo "Could not extract port number from output:"
-      echo "$output"
-      exit 1
-  fi
-  # TODO: Replace above when `services pcport` feature is shipped.
-  # https://github.com/jetify-com/devbox/pull/2784
-  # PCPORT=$(devbox services pcport) || { echo "Failed to get process-compose port"; exit 1; }
+  PCPORT=$(devbox services pcport) || { echo "Failed to get process-compose port"; exit 1; }
   
   echo ""
 
